import {StyleSheet} from 'react-native';
const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    alignContent: 'center',
    justifyContent: 'flex-start',
    flexDirection: 'column',
    backgroundColor: '#F5F6F8',
  },
  header: {
    marginTop: 20,
    flexDirection: 'row',
    width: '80%',
    justifyContent: 'space-between',
  },
  avatarContainter: {
    width: 80,
    height: 80,
    alignItems: 'center',
    justifyContent: 'center',
    left: -16,
  },
  image: {
    resizeMode: 'contain',
    width: '100%',
    height: '100%',
  },
  iconPlus: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    width: '30%',
    height: '30%',
  },
  textProfile: {
    width: '80%',
    left: 16,
    top: 5,
  },
  textProfileName: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  textProfileAdd: {},
  textProfileOtherOption: {
    marginTop: 9,
    color: '#60B939',
  },
  body: {
    flexDirection: 'column',
    marginTop: 24,
  },
  bodyStatus: {
    flexDirection: 'row',
    width: '100%',
    alignSelf: 'center',
  },
  addCounter: {
    flex: 0.33,
    alignItems: 'center',
  },
  textCounterNumber: {
    fontSize: 30,
    fontWeight: '400',
    textAlign: 'center',
  },
  textCounter: {
    fontSize: 14,
    fontWeight: '400',
    textAlign: 'center',
    left: 4,
  },
  addCounterBarrier1: {
    alignSelf: 'flex-end',
    borderRightWidth: 1,
    borderRightColor: '#C4C4C4',
    height: 35,
    position: 'absolute',
    top: 16,
  },
  bodyConfimationMethod: {
    flexDirection: 'column',
    width: '100%',
    height: 117,
    backgroundColor: '#FFFFFF',
    borderRadius: 19,
    marginTop: 30,
    alignSelf: 'center',
    justifyContent: 'center',
  },
  bodyConfimationMethodDecoration: {
    flexDirection: 'row',
    width: '100%',
    height: 30,
  },
  bodyConfimationMethodDecorationDeadSpace: {
    flex: 0.4,
    borderBottomWidth: 0.5,
    borderBottomColor: '#C4C4C4',
  },
  bodyConfimationMethodDecorationText: {
    top: 20,
  },
  bodyConfimationMethodIcons: {
    flexDirection: 'row',
    width: '80%',
    justifyContent: 'space-between',
    alignItems: 'center',
    alignSelf: 'center',
  },
  bodyConfimationMethodIcon: {
    flex: 0.25,
    height: 50,
    marginTop: 30.5,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 15,
  },
  bodySettingOptions: {
    flexDirection: 'column',
    height: 50,
    width: '100%',
    marginTop: 60,
    backgroundColor: '#FFFFFF',
    alignSelf: 'center',
  },
  bodySettingOptionsItem: {
    flexDirection: 'row',
    width: '110%',
    alignItems: 'center',
    alignSelf: 'center',
    height: 85,
    borderBottomWidth: 1,
    borderBottomColor: '#C4C4C4',
    alignSelf: 'center',
    marginTop: 10,
  },
  bodySettingOptionsItemIcon: {
    flex: 0.1,
  },
  bodySettingOptionsItemText: {
    flex: 0.8,
    fontSize: 18,
    fontWeight: '400',
    marginLeft: 12,
  },
  bodySettingOptionsItemIconBack: {
    flex: 0.1,
    marginRight: 10,
  },
  footer: {
    position: 'absolute',
    bottom: 0,
    flexDirection: 'row',
    width: '100%',
    height: 69,
    backgroundColor: '#FFFFFF',
  },
  footerItem: {
    flex: 0.25,
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerItemText: {
    fontSize: 12,
  },
});
export default styles;
